---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geoipfinder
  name: geoipfinder
  namespace: geoipfinder
spec:
  type: NodePort
  selector:
    app: geoipfinder
  ports:
  - name: geoipfinder
    port: 1323
    nodePort: 31323
    protocol: TCP

status:
  loadBalancer: {}
